name: Build solutions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get dist-upgrade
          sudo apt-get install latexmk texlive-latex-extra texlive-fonts-extra

      - name: Build PDF
        run: make solutions.pdf
