name: Compile LaTeX files

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get dist-upgrade
          sudo apt-get install latexmk texlive-latex-extra texlive-bibtex-extra texlive-fonts-extra biber

      - name: Build PDFs
        run: make all

      - name: Archive production PDFs
        uses: actions/upload-artifact@v4
        with:
          name: pdfs
          path: |
            style-guide/style-guide.pdf
            solutions.pdf
